# Generated by Django 2.1.5 on 2019-02-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Push_Notification', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='notification_tittle',
            new_name='notification_title',
        ),
    ]
